spring:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-34-202-88-122.compute-1.amazonaws.com:5432/dfpm7k8jca1mr7
    username: zobgrragyhmmsn
    password: 84c739552f4a58e1509e29e95914b243edc01b2dbf1833672ef6b7de79705877
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect